const IMPORT_PORTFOLIO_PATH: { [key: string]: string } = {
  ["/assets/portfolio/Archiving_self_1.jpg"]: require("./assets/portfolio/Archiving_self_1.jpg"),
  ["/assets/portfolio/Archiving_self_2.jpg"]: require("./assets/portfolio/Archiving_self_2.jpg"),
  ["/assets/portfolio/Archiving_self_3.jpg"]: require("./assets/portfolio/Archiving_self_3.jpg"),
  ["/assets/portfolio/Archiving_self_4.jpg"]: require("./assets/portfolio/Archiving_self_4.jpg"),
  ["/assets/portfolio/Archiving_self_5.jpg"]: require("./assets/portfolio/Archiving_self_5.jpg"),
  ["/assets/portfolio/Archiving_self_6.jpg"]: require("./assets/portfolio/Archiving_self_6.jpg"),
  ["/assets/portfolio/Archiving_self_7.jpg"]: require("./assets/portfolio/Archiving_self_7.jpg"),
  ["/assets/portfolio/Archiving_self_8.jpg"]: require("./assets/portfolio/Archiving_self_8.jpg"),
  ["/assets/portfolio/Archiving_self_9.jpg"]: require("./assets/portfolio/Archiving_self_9.jpg"),
  ["/assets/portfolio/Archiving_self_10.jpg"]: require("./assets/portfolio/Archiving_self_10.jpg"),
  ["/assets/portfolio/Archiving_self_11.jpg"]: require("./assets/portfolio/Archiving_self_11.jpg"),
  ["/assets/portfolio/Archiving_self_12.jpg"]: require("./assets/portfolio/Archiving_self_12.jpg"),
  ["/assets/portfolio/Archiving_self_13.jpg"]: require("./assets/portfolio/Archiving_self_13.jpg"),
  ["/assets/portfolio/Archiving_self_14.jpg"]: require("./assets/portfolio/Archiving_self_14.jpg"),
  ["/assets/portfolio/Archiving_self_15.jpg"]: require("./assets/portfolio/Archiving_self_15.jpg"),
  ["/assets/portfolio/Archiving_self_16.jpg"]: require("./assets/portfolio/Archiving_self_16.jpg"),
  ["/assets/portfolio/Archiving_self_17.jpg"]: require("./assets/portfolio/Archiving_self_17.jpg"),
  ["/assets/portfolio/Archiving_self_18.jpg"]: require("./assets/portfolio/Archiving_self_18.jpg"),
  ["/assets/portfolio/Archiving_self_19.jpg"]: require("./assets/portfolio/Archiving_self_19.jpg"),
  ["/assets/portfolio/the_things_we_are1.jpg"]: require("./assets/portfolio/the_things_we_are1.jpg"),
  ["/assets/portfolio/the_things_we_are2.jpg"]: require("./assets/portfolio/the_things_we_are2.jpg"),
  ["/assets/portfolio/the_things_we_are3.jpg"]: require("./assets/portfolio/the_things_we_are3.jpg"),
  ["/assets/portfolio/the_things_we_are4.jpg"]: require("./assets/portfolio/the_things_we_are4.jpg"),
  ["/assets/portfolio/the_things_we_are5.jpg"]: require("./assets/portfolio/the_things_we_are5.jpg"),
  ["/assets/portfolio/the_things_we_are6.jpg"]: require("./assets/portfolio/the_things_we_are6.jpg"),
  ["/assets/portfolio/the_things_we_are7.jpg"]: require("./assets/portfolio/the_things_we_are7.jpg"),
  ["/assets/portfolio/the_things_we_are8.jpg"]: require("./assets/portfolio/the_things_we_are8.jpg"),
  ["/assets/portfolio/the_things_we_are9.jpg"]: require("./assets/portfolio/the_things_we_are9.jpg"),
  ["/assets/portfolio/the_things_we_are10.jpg"]: require("./assets/portfolio/the_things_we_are10.jpg"),
  ["/assets/portfolio/the_things_we_are11.jpg"]: require("./assets/portfolio/the_things_we_are11.jpg"),
  ["/assets/portfolio/the_things_we_are12.jpg"]: require("./assets/portfolio/the_things_we_are12.jpg"),
  ["/assets/portfolio/the_things_we_are13.jpg"]: require("./assets/portfolio/the_things_we_are13.jpg"),
  ["/assets/portfolio/the_things_we_are14.jpg"]: require("./assets/portfolio/the_things_we_are14.jpg"),
  ["/assets/portfolio/the_things_we_are15.jpg"]: require("./assets/portfolio/the_things_we_are15.jpg"),
  ["/assets/portfolio/the_things_we_are16.jpg"]: require("./assets/portfolio/the_things_we_are16.jpg"),
  ["/assets/portfolio/Surely_we_jest1.jpg"]: require("./assets/portfolio/Surely_we_jest1.jpg"),
  ["/assets/portfolio/Surely_we_jest2.jpg"]: require("./assets/portfolio/Surely_we_jest2.jpg"),
  ["/assets/portfolio/Surely_we_jest3.jpg"]: require("./assets/portfolio/Surely_we_jest3.jpg"),
  ["/assets/portfolio/Surely_we_jest4.jpg"]: require("./assets/portfolio/Surely_we_jest4.jpg"),
  ["/assets/portfolio/Surely_we_jest5.jpg"]: require("./assets/portfolio/Surely_we_jest5.jpg"),
  ["/assets/portfolio/Surely_we_jest6.jpg"]: require("./assets/portfolio/Surely_we_jest6.jpg"),
  ["/assets/portfolio/Surely_we_jest7.jpg"]: require("./assets/portfolio/Surely_we_jest7.jpg"),
  ["/assets/portfolio/Surely_we_jest8.jpg"]: require("./assets/portfolio/Surely_we_jest8.jpg"),
  ["/assets/portfolio/Surely_we_jest9.jpg"]: require("./assets/portfolio/Surely_we_jest9.jpg"),
  ["/assets/portfolio/Surely_we_jest10.jpg"]: require("./assets/portfolio/Surely_we_jest10.jpg"),
  ["/assets/portfolio/Surely_we_jest11.jpg"]: require("./assets/portfolio/Surely_we_jest11.jpg"),
  ["/assets/portfolio/desire_machine1.jpg"]: require("./assets/portfolio/desire_machine1.jpg"),
  ["/assets/portfolio/desire_machine2.jpg"]: require("./assets/portfolio/desire_machine2.jpg"),
  ["/assets/portfolio/desire_machine3.jpg"]: require("./assets/portfolio/desire_machine3.jpg"),
  ["/assets/portfolio/desire_machine4.jpg"]: require("./assets/portfolio/desire_machine4.jpg"),
  ["/assets/portfolio/desire_machine5.jpg"]: require("./assets/portfolio/desire_machine5.jpg"),
  ["/assets/portfolio/desire_machine6.jpg"]: require("./assets/portfolio/desire_machine6.jpg"),
  ["/assets/portfolio/desire_machine7.jpg"]: require("./assets/portfolio/desire_machine7.jpg"),
  ["/assets/portfolio/desire_machine8.jpg"]: require("./assets/portfolio/desire_machine8.jpg"),
  ["/assets/portfolio/desire_machine9.jpg"]: require("./assets/portfolio/desire_machine9.jpg"),
  ["/assets/portfolio/desire_machine10.jpg"]: require("./assets/portfolio/desire_machine10.jpg"),
  ["/assets/portfolio/desire_machine11.jpg"]: require("./assets/portfolio/desire_machine11.jpg"),
  ["/assets/portfolio/desire_machine12.jpg"]: require("./assets/portfolio/desire_machine12.jpg"),
  ["/assets/portfolio/desire_machine13.jpg"]: require("./assets/portfolio/desire_machine13.jpg"),
  ["/assets/portfolio/desire_machine14.jpg"]: require("./assets/portfolio/desire_machine14.jpg"),
  ["/assets/portfolio/desire_machine15.jpg"]: require("./assets/portfolio/desire_machine15.jpg"),
  ["/assets/portfolio/Self_dramatization1.jpg"]: require("./assets/portfolio/Self_dramatization1.jpg"),
  ["/assets/portfolio/Self_dramatization2.jpg"]: require("./assets/portfolio/Self_dramatization2.jpg"),
  ["/assets/portfolio/Self_dramatization3.jpg"]: require("./assets/portfolio/Self_dramatization3.jpg"),
  ["/assets/portfolio/Self_dramatization4.jpg"]: require("./assets/portfolio/Self_dramatization4.jpg"),
  ["/assets/portfolio/Self_dramatization5.jpg"]: require("./assets/portfolio/Self_dramatization5.jpg"),
  ["/assets/portfolio/Self_dramatization6.jpg"]: require("./assets/portfolio/Self_dramatization6.jpg"),
  ["/assets/portfolio/Self_dramatization7.jpg"]: require("./assets/portfolio/Self_dramatization7.jpg"),
  ["/assets/portfolio/Self_dramatization8.jpg"]: require("./assets/portfolio/Self_dramatization8.jpg"),
  ["/assets/portfolio/Self_dramatization9.jpg"]: require("./assets/portfolio/Self_dramatization9.jpg"),
  ["/assets/portfolio/Self_dramatization10.jpg"]: require("./assets/portfolio/Self_dramatization10.jpg"),
  ["/assets/portfolio/Self_dramatization11.jpg"]: require("./assets/portfolio/Self_dramatization11.jpg"),
  ["/assets/portfolio/Self_dramatization12.jpg"]: require("./assets/portfolio/Self_dramatization12.jpg"),
  ["/assets/portfolio/Self_dramatization13.jpg"]: require("./assets/portfolio/Self_dramatization13.jpg"),
  ["/assets/portfolio/Self_dramatization14.jpg"]: require("./assets/portfolio/Self_dramatization14.jpg"),
  ["/assets/portfolio/Self_dramatization15.jpg"]: require("./assets/portfolio/Self_dramatization15.jpg"),
  ["/assets/portfolio/Self_dramatization16.jpg"]: require("./assets/portfolio/Self_dramatization16.jpg"),
  ["/assets/portfolio/Self_dramatization17.jpg"]: require("./assets/portfolio/Self_dramatization17.jpg"),
};

const IMPORT_PUBLIC_ASSETS_PATH: { [key: string]: string } = {
  ["assets/fonts/Helvetica.ttf"]: require("./assets/fonts/Helvetica.ttf"),
};

export const IMPORT_PATH: { [key: string]: string } = {
  ["/assets/png/by_tati.png"]: require("./assets/png/by_tati.png"),
  ["/assets/svg/nav_item_01.svg"]: require("./assets/svg/nav_item_01.svg"),
  ["/assets/svg/nav_item_02.svg"]: require("./assets/svg/nav_item_02.svg"),
  ["/assets/svg/nav_item_03.svg"]: require("./assets/svg/nav_item_03.svg"),
  ["/assets/svg/nav_item_04.svg"]: require("./assets/svg/nav_item_04.svg"),
  ["/assets/svg/nav_background.svg"]: require("./assets/svg/nav_background.svg"),
  ["/assets/png/instagram_black_logo.png"]: require("./assets/png/instagram_black_logo.png"),
  ["/assets/png/tati_info_profile.png"]: require("./assets/png/tati_info_profile.png"),
  ...IMPORT_PORTFOLIO_PATH,
  ...IMPORT_PUBLIC_ASSETS_PATH,
};

export const STATIC_PATH: { [key: string]: string } = {
  ["/assets/svg/nav_background.svg"]: `url("/assets/svg/nav_background.svg")`,
};
